name: Offline Test

on:
  workflow_dispatch:

jobs:
  offline-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run offline test
        env:
          TEST_STRATEGY: comprehensive
        run: |
          python offline_test.py